# Generated by Django 5.1.2 on 2024-10-08 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('descricao_produto', models.TextField(verbose_name='Descreva o produto/serviço')),
                ('categoria', models.CharField(choices=[('Simulado', 'Simulado'), ('Aulão', 'Aulão'), ('Eventos', 'Eventos'), ('Brindes', 'Brindes'), ('Documentos', 'Documentos'), ('Domínio do site', 'Domínio do site'), ('Google Meets', 'Google Meets'), ('Processo Seletivo de Alunos', 'Processo Seletivo de Alunos'), ('Processo Seletivo de Organizadores/Docentes', 'Processo Seletivo de Organizadores/Docentes'), ('Outro', 'Outro')], max_length=50)),
                ('valor_nf', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Nota Fiscal')),
                ('data_pagamento', models.DateField(verbose_name='Data do Pagamento')),
                ('comprovante', models.ImageField(upload_to='comprovantes/')),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
