# Generated by Django 5.1.1 on 2024-10-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reembolso',
            name='solicitante',
        ),
        migrations.RemoveField(
            model_name='reembolso',
            name='status',
        ),
        migrations.AddField(
            model_name='reembolso',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='comprovante',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes/'),
        ),
    ]
