# Generated by Django 5.1.2 on 2024-10-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0002_remove_reembolso_solicitante_remove_reembolso_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolso',
            name='comprovante',
            field=models.ImageField(upload_to='comprovantes/'),
        ),
    ]
