# Generated by Django 5.1.2 on 2024-10-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0003_alter_reembolso_comprovante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolso',
            name='comprovante',
            field=models.FileField(default='', upload_to='comprovantes/'),
        ),
    ]
