# Generated by Django 5.1.2 on 2024-10-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0004_alter_reembolso_comprovante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reembolso',
            name='comprovante',
        ),
        migrations.AddField(
            model_name='reembolso',
            name='comprovante_pedido',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/pedido/'),
        ),
        migrations.AddField(
            model_name='reembolso',
            name='comprovante_reembolso',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/reembolso/'),
        ),
    ]
