# Generated by Django 5.1.2 on 2024-11-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0005_remove_reembolso_comprovante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reembolso',
            name='departamento',
            field=models.CharField(choices=[('Hogwarts', 'Hogwarts'), ('Embaixada', 'Embaixada'), ('Times Square- Captação', 'Times Square- Captação'), ('Ministério', 'Ministério'), ('Times Square- Mkt', 'Times Square- Mkt'), ('Vale do Silício', 'Vale do Silício'), ('Presidência', 'Presidência'), ('Processo Seletivo', 'Processo Seletivo')], default='Hogwarts', max_length=50),
        ),
    ]
